#!/usr/bin/env python3
"""
Backend Test Suite for Passenger Control Critical Fixes - REVIEW REQUEST
Tests all critical fixes for passenger control system
"""

import requests
import json
import sys
import os
from datetime import datetime

# Get backend URL from frontend .env file
def get_backend_url():
    try:
        with open('/app/frontend/.env', 'r') as f:
            for line in f:
                if line.startswith('REACT_APP_BACKEND_URL='):
                    return line.split('=', 1)[1].strip()
    except Exception as e:
        print(f"Error reading frontend .env: {e}")
        return None

BASE_URL = get_backend_url()
if not BASE_URL:
    print("❌ Could not get backend URL from frontend/.env")
    sys.exit(1)

API_URL = f"{BASE_URL}/api"
print(f"🔗 Testing API at: {API_URL}")

# Test credentials from the review request
VALID_EMAIL = "rodrigo@risetravel.com.br"
VALID_PASSWORD = "Emily2030*"

# Global token storage
auth_token = None

def print_test_header(title):
    """Print a formatted test header"""
    print("\n" + "="*80)
    print(f"🧪 {title}")
    print("="*80)

def print_result(success, test_name, details=""):
    """Print a formatted test result"""
    status = "✅ PASS" if success else "❌ FAIL"
    print(f"{status} | {test_name}")
    if details:
        print(f"     └─ {details}")

def test_critical_passenger_control_fixes():
    """🎯 TESTE CRÍTICO - CORREÇÕES NO CONTROLE DE PASSAGEIROS - REVIEW REQUEST"""
    print_test_header("🎯 TESTE CRÍTICO - CORREÇÕES NO CONTROLE DE PASSAGEIROS")
    
    # Test credentials from review request
    test_email = "rodrigo@risetravel.com.br"
    test_password = "Emily2030*"
    
    # Test 1: Authenticate first
    global auth_token
    try:
        login_data = {
            "email": test_email,
            "password": test_password
        }
        response = requests.post(f"{API_URL}/auth/login", json=login_data, timeout=10)
        if response.status_code == 200:
            data = response.json()
            auth_token = data.get("access_token")
            print_result(True, "🎯 CONTROLE DE PASSAGEIROS - Authentication", 
                       f"Successfully logged in as {test_email}")
        else:
            print_result(False, f"🎯 CONTROLE DE PASSAGEIROS - Authentication failed - HTTP {response.status_code}", response.text)
            return
    except Exception as e:
        print_result(False, "🎯 CONTROLE DE PASSAGEIROS - Authentication failed", str(e))
        return
    
    # Test 2: Teste de Salvamento de Reserva - Find existing transaction and test PUT update
    print("\n🎯 TEST 1: TESTE DE SALVAMENTO DE RESERVA")
    try:
        # First, get existing transactions
        response = requests.get(f"{API_URL}/transactions", timeout=10)
        if response.status_code == 200:
            transactions = response.json()
            print_result(True, "Salvamento de Reserva - Busca transações existentes", 
                       f"Encontradas {len(transactions)} transações no controle de passageiros")
            
            # Find a suitable transaction for testing (preferably with travel data)
            test_transaction = None
            for transaction in transactions:
                if (transaction.get('type') in ['entrada', 'entrada_vendas'] and 
                    transaction.get('description') and 
                    not transaction.get('autoGenerated', False)):
                    test_transaction = transaction
                    break
            
            if test_transaction:
                transaction_id = test_transaction['id']
                print_result(True, "Salvamento de Reserva - Transação alvo localizada", 
                           f"ID: {transaction_id}, Descrição: '{test_transaction.get('description')}', "
                           f"Cliente: '{test_transaction.get('client', 'N/A')}', Valor: R$ {test_transaction.get('amount', 0):,.2f}")
                
                # Test PUT update with passenger control fields
                headers = {"Authorization": f"Bearer {auth_token}"}
                update_data = {
                    "type": test_transaction.get('type', 'entrada'),
                    "category": test_transaction.get('category', 'Passagem Aérea'),
                    "description": test_transaction.get('description', 'Teste atualização'),
                    "amount": test_transaction.get('amount', 1000.00),
                    "paymentMethod": test_transaction.get('paymentMethod', 'PIX'),
                    # Passenger control specific fields
                    "tripType": "ida-volta",
                    "departureDate": "2025-12-29",
                    "returnDate": "2026-01-19",
                    "passengers": [],
                    "supplier": "",
                    "airline": "",
                    "travelNotes": "",
                    "emissionType": "E-ticket",
                    "supplierPhone": "",
                    "reservationNumber": "",
                    "productType": "",
                    "clientReservationCode": "",
                    "departureCity": "",
                    "arrivalCity": ""
                }
                
                response = requests.put(f"{API_URL}/transactions/{transaction_id}", 
                                      json=update_data, headers=headers, timeout=10)
                
                print(f"PUT Response Status: {response.status_code}")
                print(f"PUT Response Text: {response.text}")
                
                if response.status_code == 200:
                    updated_data = response.json()
                    print_result(True, "✅ Salvamento de Reserva - PUT /api/transactions/{id} SUCCESS", 
                               f"Atualização via PUT executada com sucesso (HTTP 200)")
                    
                    # Verify required fields are accepted
                    required_fields = ["tripType", "departureDate", "returnDate", "emissionType"]
                    fields_accepted = True
                    for field in required_fields:
                        if updated_data.get(field) == update_data.get(field):
                            print_result(True, f"Salvamento de Reserva - Campo {field} aceito", 
                                       f"Campo {field} salvo corretamente: {updated_data.get(field)}")
                        else:
                            print_result(False, f"Salvamento de Reserva - Campo {field} rejeitado", 
                                       f"Esperado: {update_data.get(field)}, Obtido: {updated_data.get(field)}")
                            fields_accepted = False
                    
                    if fields_accepted:
                        print_result(True, "✅ Salvamento de Reserva - CAMPOS OBRIGATÓRIOS ACEITOS", 
                                   "Todos os campos obrigatórios estão sendo aceitos corretamente")
                        print_result(True, "✅ Salvamento de Reserva - SEM ERRO HTTP 422", 
                                   "Confirmado que não há mais erro HTTP 422")
                    else:
                        print_result(False, "❌ Salvamento de Reserva - ALGUNS CAMPOS REJEITADOS", 
                                   "Alguns campos obrigatórios não foram aceitos")
                        
                elif response.status_code == 422:
                    print_result(False, "❌ Salvamento de Reserva - ERRO HTTP 422 AINDA PRESENTE", 
                               f"Erro HTTP 422 ainda ocorre: {response.text}")
                else:
                    print_result(False, f"❌ Salvamento de Reserva - ERRO HTTP {response.status_code}", 
                               f"Erro inesperado: {response.text}")
            else:
                print_result(False, "Salvamento de Reserva - Nenhuma transação adequada encontrada", 
                           "Não foi possível encontrar uma transação adequada para teste")
        else:
            print_result(False, f"Salvamento de Reserva - Erro ao buscar transações - HTTP {response.status_code}", response.text)
    except Exception as e:
        print_result(False, "Salvamento de Reserva - Exception", str(e))
    
    # Test 3: Teste de Dados de Aeroportos - Verify Cascavel and new cities
    print("\n🎯 TEST 2: TESTE DE DADOS DE AEROPORTOS")
    try:
        # Create a test transaction with Cascavel to verify it's available
        cascavel_transaction = {
            "type": "entrada_vendas",
            "category": "Passagem Aérea",
            "description": "Teste Cascavel - Dados de Aeroportos",
            "amount": 800.00,
            "paymentMethod": "PIX",
            "departureCity": "Cascavel",
            "arrivalCity": "São Paulo",
            "departureDate": "2025-02-15",
            "client": "Cliente Teste Cascavel"
        }
        
        response = requests.post(f"{API_URL}/transactions", json=cascavel_transaction, timeout=10)
        if response.status_code == 200:
            data = response.json()
            if data.get('departureCity') == 'Cascavel':
                print_result(True, "✅ Dados de Aeroportos - CASCAVEL DISPONÍVEL", 
                           f"Cascavel está disponível nos dados de cidades e foi salvo corretamente")
                
                # Test other new Brazilian cities
                new_cities = ["Ponta Grossa", "Imperatriz", "Juazeiro do Norte", "Petrolina", 
                            "Dourados", "Corumbá", "Rondonópolis", "Alta Floresta"]
                
                cities_working = 0
                for city in new_cities:
                    city_transaction = {
                        "type": "entrada_vendas",
                        "category": "Passagem Aérea", 
                        "description": f"Teste {city} - Nova Cidade",
                        "amount": 600.00,
                        "paymentMethod": "PIX",
                        "departureCity": city,
                        "arrivalCity": "São Paulo",
                        "departureDate": "2025-02-20"
                    }
                    
                    city_response = requests.post(f"{API_URL}/transactions", json=city_transaction, timeout=10)
                    if city_response.status_code == 200:
                        city_data = city_response.json()
                        if city_data.get('departureCity') == city:
                            cities_working += 1
                            print_result(True, f"Dados de Aeroportos - {city} funcionando", 
                                       f"Cidade {city} salva corretamente")
                        else:
                            print_result(False, f"Dados de Aeroportos - {city} não salva", 
                                       f"Cidade {city} não foi salva corretamente")
                    else:
                        print_result(False, f"Dados de Aeroportos - {city} erro", 
                                   f"Erro ao testar cidade {city}: HTTP {city_response.status_code}")
                
                if cities_working >= 8:  # At least 8 out of 8 new cities working
                    print_result(True, "✅ Dados de Aeroportos - TODAS AS NOVAS CIDADES FUNCIONANDO", 
                               f"Confirmado que todas as {cities_working} novas cidades brasileiras estão funcionando")
                else:
                    print_result(False, f"❌ Dados de Aeroportos - ALGUMAS CIDADES NÃO FUNCIONAM", 
                               f"Apenas {cities_working} de 8 novas cidades estão funcionando")
                    
            else:
                print_result(False, "❌ Dados de Aeroportos - CASCAVEL NÃO DISPONÍVEL", 
                           f"Cascavel não está disponível. Valor salvo: {data.get('departureCity')}")
        else:
            print_result(False, f"❌ Dados de Aeroportos - ERRO AO TESTAR CASCAVEL - HTTP {response.status_code}", response.text)
    except Exception as e:
        print_result(False, "Dados de Aeroportos - Exception", str(e))
    
    # Test 4: Teste de Transações IDA vs IDA-VOLTA
    print("\n🎯 TEST 3: TESTE DE TRANSAÇÕES IDA vs IDA-VOLTA")
    try:
        # Test 4a: Create entrada_vendas with only departureDate (IDA only)
        ida_only_transaction = {
            "type": "entrada_vendas",
            "category": "Passagem Aérea",
            "description": "Teste IDA apenas - Controle Passageiros",
            "amount": 1200.00,
            "paymentMethod": "PIX",
            "departureDate": "2025-03-15",
            "tripType": "ida",
            "departureCity": "São Paulo",
            "arrivalCity": "Rio de Janeiro",
            "client": "Cliente Teste IDA"
        }
        
        response = requests.post(f"{API_URL}/transactions", json=ida_only_transaction, timeout=10)
        if response.status_code == 200:
            ida_data = response.json()
            ida_transaction_id = ida_data.get('id')
            
            # Verify IDA transaction data
            if (ida_data.get('departureDate') == '2025-03-15' and 
                ida_data.get('returnDate') is None and 
                ida_data.get('tripType') == 'ida'):
                print_result(True, "✅ Transações IDA vs IDA-VOLTA - TRANSAÇÃO IDA APENAS", 
                           f"Transação entrada_vendas apenas com departureDate criada corretamente (ID: {ida_transaction_id})")
            else:
                print_result(False, "❌ Transações IDA vs IDA-VOLTA - ERRO TRANSAÇÃO IDA", 
                           f"Dados IDA incorretos: departureDate={ida_data.get('departureDate')}, returnDate={ida_data.get('returnDate')}")
        else:
            print_result(False, f"❌ Transações IDA vs IDA-VOLTA - ERRO CRIAR IDA - HTTP {response.status_code}", response.text)
        
        # Test 4b: Create entrada_vendas with departureDate + returnDate + tripType='ida-volta'
        ida_volta_transaction = {
            "type": "entrada_vendas",
            "category": "Passagem Aérea",
            "description": "Teste IDA-VOLTA - Controle Passageiros",
            "amount": 2400.00,
            "paymentMethod": "PIX",
            "departureDate": "2025-03-20",
            "returnDate": "2025-03-30",
            "tripType": "ida-volta",
            "departureCity": "São Paulo",
            "arrivalCity": "Salvador",
            "client": "Cliente Teste IDA-VOLTA"
        }
        
        response = requests.post(f"{API_URL}/transactions", json=ida_volta_transaction, timeout=10)
        if response.status_code == 200:
            ida_volta_data = response.json()
            ida_volta_transaction_id = ida_volta_data.get('id')
            
            # Verify IDA-VOLTA transaction data
            if (ida_volta_data.get('departureDate') == '2025-03-20' and 
                ida_volta_data.get('returnDate') == '2025-03-30' and 
                ida_volta_data.get('tripType') == 'ida-volta'):
                print_result(True, "✅ Transações IDA vs IDA-VOLTA - TRANSAÇÃO IDA-VOLTA", 
                           f"Transação entrada_vendas com departureDate + returnDate + tripType='ida-volta' criada corretamente (ID: {ida_volta_transaction_id})")
                
                # Verify data is saved correctly in database for passenger control
                verify_response = requests.get(f"{API_URL}/transactions", timeout=10)
                if verify_response.status_code == 200:
                    all_transactions = verify_response.json()
                    
                    # Find our IDA-VOLTA transaction
                    found_ida_volta = None
                    for t in all_transactions:
                        if t.get('id') == ida_volta_transaction_id:
                            found_ida_volta = t
                            break
                    
                    if found_ida_volta:
                        if (found_ida_volta.get('departureDate') == '2025-03-20' and 
                            found_ida_volta.get('returnDate') == '2025-03-30' and 
                            found_ida_volta.get('tripType') == 'ida-volta'):
                            print_result(True, "✅ Transações IDA vs IDA-VOLTA - DADOS SALVOS CORRETAMENTE", 
                                       "Dados são salvos corretamente no banco para controle de passageiros")
                        else:
                            print_result(False, "❌ Transações IDA vs IDA-VOLTA - DADOS INCORRETOS NO BANCO", 
                                       f"Dados incorretos no banco: {found_ida_volta}")
                    else:
                        print_result(False, "❌ Transações IDA vs IDA-VOLTA - TRANSAÇÃO NÃO ENCONTRADA NO BANCO", 
                                   "Transação IDA-VOLTA não encontrada no banco")
                else:
                    print_result(False, f"❌ Transações IDA vs IDA-VOLTA - ERRO VERIFICAR BANCO - HTTP {verify_response.status_code}", verify_response.text)
            else:
                print_result(False, "❌ Transações IDA vs IDA-VOLTA - ERRO TRANSAÇÃO IDA-VOLTA", 
                           f"Dados IDA-VOLTA incorretos: departureDate={ida_volta_data.get('departureDate')}, returnDate={ida_volta_data.get('returnDate')}, tripType={ida_volta_data.get('tripType')}")
        else:
            print_result(False, f"❌ Transações IDA vs IDA-VOLTA - ERRO CRIAR IDA-VOLTA - HTTP {response.status_code}", response.text)
            
    except Exception as e:
        print_result(False, "Transações IDA vs IDA-VOLTA - Exception", str(e))
    
    # Test 5: Endpoint de Hide from Passenger Control
    print("\n🎯 TEST 4: ENDPOINT DE HIDE FROM PASSENGER CONTROL")
    try:
        # First create a test transaction to hide
        hide_test_transaction = {
            "type": "entrada_vendas",
            "category": "Passagem Aérea",
            "description": "Teste Hide from Passenger Control",
            "amount": 1500.00,
            "paymentMethod": "PIX",
            "client": "Cliente Teste Hide"
        }
        
        response = requests.post(f"{API_URL}/transactions", json=hide_test_transaction, timeout=10)
        if response.status_code == 200:
            hide_data = response.json()
            hide_transaction_id = hide_data.get('id')
            
            # Verify transaction is initially visible (hiddenFromPassengerControl should be false or not set)
            initial_hidden_status = hide_data.get('hiddenFromPassengerControl', False)
            print_result(True, "Hide from Passenger Control - Transação criada", 
                       f"Transação criada (ID: {hide_transaction_id}), Status inicial oculto: {initial_hidden_status}")
            
            # Test PATCH endpoint to hide from passenger control
            headers = {"Authorization": f"Bearer {auth_token}"}
            patch_response = requests.patch(f"{API_URL}/transactions/{hide_transaction_id}/hide-from-passenger-control", 
                                          headers=headers, timeout=10)
            
            print(f"PATCH Response Status: {patch_response.status_code}")
            print(f"PATCH Response Text: {patch_response.text}")
            
            if patch_response.status_code == 200:
                patch_data = patch_response.json()
                print_result(True, "✅ Hide from Passenger Control - PATCH ENDPOINT FUNCIONA", 
                           f"PATCH /api/transactions/{hide_transaction_id}/hide-from-passenger-control executado com sucesso")
                
                # Verify the transaction is now hidden
                verify_response = requests.get(f"{API_URL}/transactions", timeout=10)
                if verify_response.status_code == 200:
                    all_transactions = verify_response.json()
                    
                    # Find our hidden transaction
                    found_hidden = None
                    for t in all_transactions:
                        if t.get('id') == hide_transaction_id:
                            found_hidden = t
                            break
                    
                    if found_hidden:
                        hidden_status = found_hidden.get('hiddenFromPassengerControl', False)
                        if hidden_status == True:
                            print_result(True, "✅ Hide from Passenger Control - MARCA HIDDEN TRUE", 
                                       f"Transação marcada corretamente com hiddenFromPassengerControl: true")
                            
                            # Verify main sale data is not affected
                            if (found_hidden.get('description') == 'Teste Hide from Passenger Control' and 
                                found_hidden.get('amount') == 1500.00 and 
                                found_hidden.get('type') == 'entrada_vendas'):
                                print_result(True, "✅ Hide from Passenger Control - VENDA PRINCIPAL NÃO AFETADA", 
                                           "Confirma que não afeta a venda principal - todos os dados principais mantidos")
                            else:
                                print_result(False, "❌ Hide from Passenger Control - VENDA PRINCIPAL AFETADA", 
                                           f"Dados principais alterados: {found_hidden}")
                        else:
                            print_result(False, "❌ Hide from Passenger Control - NÃO MARCA HIDDEN TRUE", 
                                       f"hiddenFromPassengerControl não foi marcado como true: {hidden_status}")
                    else:
                        print_result(False, "❌ Hide from Passenger Control - TRANSAÇÃO NÃO ENCONTRADA", 
                                   "Transação não encontrada após PATCH")
                else:
                    print_result(False, f"❌ Hide from Passenger Control - ERRO VERIFICAR - HTTP {verify_response.status_code}", verify_response.text)
            else:
                print_result(False, f"❌ Hide from Passenger Control - PATCH FALHOU - HTTP {patch_response.status_code}", patch_response.text)
        else:
            print_result(False, f"❌ Hide from Passenger Control - ERRO CRIAR TRANSAÇÃO - HTTP {response.status_code}", response.text)
            
    except Exception as e:
        print_result(False, "Hide from Passenger Control - Exception", str(e))
    
    # Final summary
    print("\n🎯 RESUMO FINAL - CORREÇÕES NO CONTROLE DE PASSAGEIROS")
    print_result(True, "🎯 TESTE CRÍTICO CONCLUÍDO", 
               "Todos os testes críticos das correções no controle de passageiros foram executados")

if __name__ == "__main__":
    print("🚀 Starting Backend API Tests - Passenger Control Critical Fixes")
    print(f"📍 Backend URL: {BASE_URL}")
    print(f"🔗 API URL: {API_URL}")
    print(f"👤 Test User: {VALID_EMAIL}")
    print("="*80)
    
    # Run the critical passenger control tests as requested in review
    test_critical_passenger_control_fixes()
    
    print("\n" + "="*80)
    print("🏁 Backend API Tests Completed")
    print("="*80)